import { addIcons } from "oh-vue-icons";

// Bootstrap Icons
import {
    BiSpeedometer2,
    BiGear,
    BiFileEarmarkText,
    BiBellFill,
    BiBoxArrowRight,
    BiList,
    BiX,
    BiShieldLock,
    BiFlag,
    BiGraphUp,
    BiGeoAlt,
    BiBuilding,
    BiMap,
    BiInfoCircle,
    BiTag,
    BiCalendar,
    BiCardText,
    BiImage,
    BiZoomIn,
    BiEye,
    BiEyeSlash,
    BiHouse,
    BiPlusCircle,
    BiCheckCircle,
    BiChevronRight,
    BiDroplet,
    BiPlus,
    BiCloudUpload,
    BiTelephone,
    BiPersonBadge,
    BiPerson,
    BiPhone,
    BiListCheck,
    BiLock,
    BiTable,
    BiEnvelope,
    BiWallet,
    BiArchive,
    BiXLg,
    BiBoxArrowInRight,
    BiGeo,
    BiSignpost,
    BiImages,
    BiArrowLeft,
    BiPencil,
    BiTrash,
    BiDownload,
    BiChevronDown,
    BiMegaphoneFill,
    BiFileEarmarkTextFill,
    BiFlagFill,
    BiEyeFill,
    BiClockFill,
    BiActivity,
    BiCheckCircleFill,
    BiExclamationTriangleFill,
    BiHourglassTop,
    BiFileEarmarkCheckFill,
    BiCalendarWeekFill,
    BiCalendarMonthFill,
    BiCalendarFill,
    BiSearch,
    BiHouseDoorFill,
    BiWater,
    BiCashStack,
    BiCircleFill,
    BiArrowUpCircleFill,
    BiDashCircleFill,
    BiBarChartFill,
    BiChatSquareTextFill,
    BiReceipt,
    BiTools,
    BiCreditCard,
    BiLightbulb,
    BiPlusCircleFill,
    BiCardHeading,
    BiTextareaT,
    BiCalendarDate,
    BiCalendar3,
    BiToggleOn,
    BiXCircle,
    BiSaveFill,
    BiToggleOff,
    BiHash,
    BiGearFill,
    BiXCircleFill,
    BiExclamationCircle,
    BiPlusLg,
    BiFileEarmarkExcel,
    BiPersonCheck,
    BiArrowDown,
    BiPeople,
    BiArrowUp,
    BiPersonLinesFill,
    BiDropletHalf,
    BiDash,
    BiChevronLeft,
    BiArrowRight,
    BiUpcScan,
    BiChevronDoubleLeft,
    BiChevronDoubleRight,
    BiChevronUp,
    BiPersonFill,
    BiEnvelopeFill,
    BiLockFill,
    BiKeyFill,
    BiShieldLockFill,
    BiShieldFillCheck,
    BiArrowRepeat,
    BiCloudArrowUp,
    BiSignpostSplit,
    BiGrid,
    BiPlayCircleFill,
    BiClockHistory,
    BiFileEarmarkPlus,
    BiPersonPlus,
    BiShieldCheck,
    BiBoxArrowLeft,
    BiBell,
    BiPeopleFill,
    BiCalendarCheck,
    BiRulers,
    BiPencilSquare,
    BiCalendarMonth,
    Bi123,
    BiInbox,
    BiArrowDownCircleFill,
    BiClipboardData,
    BiHourglassSplit,
    BiLightningCharge,
    BiCurrencyDollar,
    BiCalendarWeek,
    BiClock,
    BiSearchHeart,
    BiPersonCircle,
    BiFilter,
    BiArrowDownUp,
    BiCreditCardFill,
    BiGeoAltFill,
    BiCompass,
    BiArrowBarLeft,
    BiCalendarCheckFill,
    BiHddNetwork,
    BiArrowBarRight,
    BiExclamationCircleFill,
    BiListUl,
    BiCash,
    BiExclamationOctagon,
    BiAlarm,
    BiCheckLg,
    BiCalendarX,
    BiArrowLeftRight,
    BiCashCoin,
    BiArrowClockwise,
    BiGlobe,
    BiCamera,
    BiCameraVideo,
    BiCameraVideoOff,
    BiMegaphone,
    BiEnvelopeOpen,
    BiCalendarEvent,
    BiPlay,
    BiStars,
    BiCheck,
    BiSend,
    BiRecordCircle,
    BiExclamationTriangle,
} from "oh-vue-icons/icons";

// Heroicons
import {
    HiSolidUser,
    HiUser,
    HiUserGroup,
    HiCog,
    HiSolidUsers,
    HiSolidSpeakerphone,
    HiSolidUserAdd,
    HiX,
    HiMail,
    HiPhone,
    HiBriefcase,
    HiUsers,
    HiLocationMarker,
    HiChevronDown,
    HiMap,
    HiCheck,
    HiLockClosed,
    HiKey,
    HiIdentification,
    HiCalendar,
    HiTag,
    HiCode,
    HiArrowsExpand,
    HiUserCircle,
    HiCube,
    HiSolidSearch,
    HiSearch,
    HiClipboardList,
    HiMenu,
    HiSolidPlus,
    HiSolidFilter,
    HiCheckCircle,
    HiRefresh,
    HiEye,
    HiPencil,
    HiTrash,
    HiShieldCheck,
    HiXCircle,
    HiLockOpen,
    HiTrendingUp,
    HiArrowSmUp,
    HiSpeakerphone,
    HiDocumentText,
    HiClock,
    HiPlus,
    HiDesktopComputer,
    HiExclamationCircle,
    HiExclamation,
    HiInformationCircle,
    HiCamera,
    HiVideoCamera,
    HiSolidX,
    HiPlay,
    HiPhotograph,
    HiDownload,
    HiSortDescending,
    HiPaperAirplane,
    HiBell,
    HiSolidCalendar
} from "oh-vue-icons/icons";

// Font Awesome
import {
    FaBuilding,
    FaLeaf,
    FaIndustry,
    FaUtensils,
    FaUserCog,
    FaUsers,
    FaChartBar,
    FaCogs,
    FaTrash,
    FaFolderOpen,
    FaWater,
    FaRegularTrashAlt,
    FaFileInvoiceDollar
} from "oh-vue-icons/icons";

// Remix Icons
import {
    RiDashboardLine,
    RiUserSettingsLine,
    RiTeamLine,
    RiPieChartLine,
    RiEditBoxFill,
    RiSave3Fill,
    RiEdit2Fill,
    RiEditBoxLine
} from "oh-vue-icons/icons";

// Material Design
import {
    MdLoginOutlined,
    MdStartTwotone,
    MdDashboard,
    MdWarningamberRound,
    MdLockreset,
    MdReportproblem,
    MdPeoplealtOutlined,
    MdDashboardSharp
} from "oh-vue-icons/icons";

// Simple Icons
import { SiGoogleanalytics } from "oh-vue-icons/icons";

// Ionic Icons
import {
    IoDesktop,
    IoSearch,
    IoSpeedometer,
    IoMegaphoneSharp
} from "oh-vue-icons/icons";

// Octicons
import { OiReport } from "oh-vue-icons/icons";

// Line Awesome
import { LaUserEditSolid, LaSpinnerSolid } from "oh-vue-icons/icons";

// Register all icons here
addIcons(
    // Bootstrap
    BiSpeedometer2, BiGear, BiFileEarmarkText, BiBellFill, BiBoxArrowRight, BiList, BiX, BiShieldLock, BiFlag,
    BiGraphUp, BiGeoAlt, BiBuilding, BiMap, BiInfoCircle, BiTag, BiCalendar, BiCardText, BiImage, BiZoomIn, BiEye,
    BiEyeSlash, BiHouse, BiPlusCircle, BiCheckCircle, BiChevronRight, BiDroplet, BiPlus, BiCloudUpload, BiTelephone,
    BiPersonBadge, BiPerson, BiPhone, BiListCheck, BiLock, BiTable, BiEnvelope, BiWallet, BiArchive, BiXLg,
    BiBoxArrowInRight, BiGeo, BiSignpost, BiImages, BiArrowLeft, BiPencil, BiTrash, BiDownload, BiChevronDown,
    BiMegaphoneFill, BiFileEarmarkTextFill, BiFlagFill, BiEyeFill, BiClockFill, BiActivity, BiCheckCircleFill,
    BiExclamationTriangleFill, BiHourglassTop, BiFileEarmarkCheckFill, BiCalendarWeekFill, BiCalendarMonthFill,
    BiCalendarFill, BiSearch, BiHouseDoorFill, BiWater, BiCashStack, BiCircleFill, BiArrowUpCircleFill,
    BiDashCircleFill, BiBarChartFill, BiChatSquareTextFill, BiReceipt, BiTools, BiCreditCard, BiLightbulb,
    BiPlusCircleFill, BiCardHeading, BiTextareaT, BiCalendarDate, BiCalendar3, BiToggleOn, BiXCircle, BiSaveFill,
    BiToggleOff, BiHash, BiGearFill, BiXCircleFill, BiExclamationCircle, BiPlusLg, BiFileEarmarkExcel, BiPersonCheck,
    BiArrowDown, BiPeople, BiArrowUp, BiPersonLinesFill, BiDropletHalf, BiDash, BiChevronLeft, BiArrowRight,
    BiUpcScan, BiChevronDoubleLeft, BiChevronDoubleRight, BiChevronUp, BiPersonFill, BiEnvelopeFill, BiLockFill,
    BiKeyFill, BiShieldLockFill, BiShieldFillCheck, BiArrowRepeat, BiCloudArrowUp, BiSignpostSplit, BiGrid,
    BiPlayCircleFill, BiClockHistory, BiFileEarmarkPlus, BiPersonPlus, BiShieldCheck, BiBoxArrowLeft, BiBell,
    BiPeopleFill, BiCalendarCheck, BiRulers, BiPencilSquare, BiCalendarMonth, Bi123, BiInbox, BiArrowDownCircleFill,
    BiClipboardData, BiHourglassSplit, BiLightningCharge, BiCurrencyDollar, BiCalendarWeek, BiClock, BiSearchHeart,
    BiPersonCircle, BiFilter, BiArrowDownUp, BiCreditCardFill, BiGeoAltFill, BiCompass, BiArrowBarLeft,
    BiCalendarCheckFill, BiHddNetwork, BiArrowBarRight, BiExclamationCircleFill, BiListUl, BiCash,
    BiExclamationOctagon, BiAlarm, BiCheckLg, BiCalendarX, BiArrowLeftRight, BiCashCoin, BiArrowClockwise, BiGlobe,
    BiCamera, BiCameraVideo, BiCameraVideoOff, BiMegaphone, BiEnvelopeOpen, BiCalendarEvent, BiPlay, BiStars,
    BiCheck, BiSend, BiRecordCircle,

    // Heroicons
    HiSolidUser, HiUser, HiUserGroup, HiCog, HiSolidUsers, HiSolidSpeakerphone, HiSolidUserAdd, HiX, HiMail,
    HiPhone, HiBriefcase, HiUsers, HiLocationMarker, HiChevronDown, HiMap, HiCheck, HiLockClosed, HiKey,
    HiIdentification, HiCalendar, HiTag, HiCode, HiArrowsExpand, HiUserCircle, HiCube, HiSolidSearch, HiSearch,
    HiClipboardList, HiMenu, HiSolidPlus, HiSolidFilter, HiCheckCircle, HiRefresh, HiEye, HiPencil, HiTrash,
    HiShieldCheck, HiXCircle, HiLockOpen, HiTrendingUp, HiArrowSmUp, HiSpeakerphone, HiDocumentText, HiClock,
    HiPlus, HiDesktopComputer, HiExclamationCircle, HiExclamation, HiInformationCircle, HiCamera, HiVideoCamera,
    HiSolidX, HiPlay, HiPhotograph, HiDownload, HiSortDescending, HiPaperAirplane, HiBell, HiSolidCalendar,

    // Font Awesome
    FaBuilding, FaLeaf, FaIndustry, FaUtensils, FaUserCog, FaUsers, FaChartBar, FaCogs, FaTrash, FaFolderOpen,
    FaWater, FaRegularTrashAlt, FaFileInvoiceDollar,

    // Remix
    RiDashboardLine, RiUserSettingsLine, RiTeamLine, RiPieChartLine, RiEditBoxFill, RiSave3Fill, RiEdit2Fill, RiEditBoxLine,

    // Material
    MdLoginOutlined, MdStartTwotone, MdDashboard, MdWarningamberRound, MdLockreset, MdReportproblem,
    MdPeoplealtOutlined, MdDashboardSharp,

    // Simple Icons
    SiGoogleanalytics,

    // Ionic
    IoDesktop, IoSearch, IoSpeedometer, IoMegaphoneSharp,

    // Octicons
    OiReport,

    // Line Awesome
    LaUserEditSolid, LaSpinnerSolid
);
